pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                build job: 'BuildSampleApp'
            }
        }

        stage('Test') {
            steps {
                build job: 'TestSampleApp'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker stop samplerunning || true'
                sh 'docker rm samplerunning || true'
            }
        }
    }
}
